-- Write your PostgreSQL query statement below
WITH LAST_6_DAYS AS (
    SELECT DISTINCT VISITED_ON AS DT
    FROM CUSTOMER ORDER BY VISITED_ON OFFSET 6
)
SELECT
A.DT AS VISITED_ON, 
SUM(B.AMOUNT) AS AMOUNT,
ROUND((SUM(B.AMOUNT)*1.0)/(7),2) AS AVERAGE_AMOUNT
FROM LAST_6_DAYS A JOIN CUSTOMER B ON 
  B.VISITED_ON between a.dt -6 and a.dt
GROUP BY A.DT
