-- Write your PostgreSQL query statement below
-- 
-- 
-- 
-- 
-- 
-- 
-- 
-- SELECT
-- ROUND(SUM(I.TIV_2016)::DECIMAL,2) AS TIV_2016
-- FROM INSURANCE I 
-- WHERE I.TIV_2015 IN (SELECT TIV_2015 FROM INSURANCE I2 WHERE I.PID <> I2.PID ) AND 
-- (I.LAT,I.LON) NOT IN (SELECT I3.LAT, I3.LON FROM INSURANCE I3 WHERE I.PID <> I3.PID)


SELECT 
ROUND(SUM(TIV_2016)::NUMERIC, 2) AS TIV_2016
FROM (
SELECT
*,
COUNT(*) OVER(PARTITION BY TIV_2015) AS TIV_2015_CNT,
COUNT(*) OVER(PARTITION BY LAT,LON) AS LOC_CNT
FROM INSURANCE
) A 
WHERE TIV_2015_CNT > 1 AND LOC_CNT = 1