# Write your MySQL query statement below
SELECT 
E1.EMPLOYEE_ID
FROM EMPLOYEES E1 INNER JOIN EMPLOYEES E2 
ON E1.MANAGER_ID = E2.EMPLOYEE_ID 
INNER JOIN EMPLOYEES E3 ON E2.MANAGER_ID = E3.EMPLOYEE_ID
WHERE E3.MANAGER_ID = 1 AND E1.EMPLOYEE_ID != 1