# Write your MySQL query statement below

 SELECT E.NAME FROM EMPLOYEE M INNER JOIN EMPLOYEE E ON 
 M.MANAGERID = E.ID
GROUP BY E.ID HAVING COUNT(*) >= 5;


-- SELECT NAME FROM EMPLOYEE WHERE ID IN (SELECT MANAGERID FROM EMPLOYEE
-- GROUP BY MANAGERID HAVING COUNT(*) >= 5);