# Write your MySQL query statement below

SELECT 
ST.STUDENT_ID, ST.STUDENT_NAME, SB.SUBJECT_NAME, IFNULL(COUNT(E.STUDENT_ID),0) AS ATTENDED_EXAMS
FROM STUDENTS ST CROSS JOIN SUBJECTS SB 
LEFT JOIN EXAMINATIONS E ON ST.STUDENT_ID = E.STUDENT_ID AND SB.SUBJECT_NAME = E.SUBJECT_NAME
GROUP BY ST.STUDENT_ID, ST.STUDENT_NAME, SB.SUBJECT_NAME
ORDER BY ST.STUDENT_ID, SB.SUBJECT_NAME