-- Write your PostgreSQL query statement below
WITH STUDENTS_SUBJECTS as (
    SELECT 
        STUDENT_ID, STUDENT_NAME, SUBJECT_NAME
    FROM STUDENTS CROSS JOIN SUBJECTS 
),
EXAMS AS (
    SELECT 
    SS.STUDENT_ID,
    SS.STUDENT_NAME, 
    SS.SUBJECT_NAME,
    E.SUBJECT_NAME AS ENAME
    FROM STUDENTS_SUBJECTS SS 
    LEFT JOIN EXAMINATIONS E
    ON SS.STUDENT_ID = E.STUDENT_ID AND SS.SUBJECT_NAME = E.SUBJECT_NAME
)
SELECT
    E.STUDENT_ID, E.STUDENT_NAME, E.SUBJECT_NAME,
    COALESCE(COUNT(E.ENAME), 0) AS ATTENDED_EXAMS
FROM EXAMS E 
    GROUP BY E.STUDENT_ID, E.STUDENT_NAME, E.SUBJECT_NAME
ORDER BY E.STUDENT_ID, E.SUBJECT_NAME
