-- Write your PostgreSQL query statement below
WITH RANKED_SALES AS (
SELECT 
*, RANK() OVER(PARTITION BY PRODUCT_ID ORDER BY YEAR) AS RNK
FROM SALES S 
)
SELECT PRODUCT_ID, YEAR AS FIRST_YEAR, QUANTITY, PRICE FROM RANKED_SALES WHERE RNK = 1
