-- Write your PostgreSQL query statement below
WITH RED_SALES_PEOPLE AS (
    SELECT 
    SALES_ID
    FROM ORDERS O JOIN COMPANY C ON O.COM_ID = C.COM_ID 
    WHERE C.NAME = 'RED'
)
SELECT
NAME FROM SALESPERSON 
WHERE SALES_ID NOT IN (SELECT SALES_ID FROM RED_SALES_PEOPLE)
