-- Write your PostgreSQL query statement below
WITH ALL_SEATS AS (
    SELECT *, LAG(STUDENT) OVER(ORDER BY ID) AS PREV,
    LEAD(STUDENT) OVER(ORDER BY ID) AS NEXT
    FROM SEAT
)
SELECT 
    ID, 
    CASE WHEN ID%2 = 1 THEN COALESCE(NEXT, STUDENT) ELSE PREV END AS STUDENT 
    FROM ALL_SEATS
