# Write your MySQL query statement below


SELECT 
E.EMPLOYEE_ID, E.NAME, COUNT(DISTINCT M.EMPLOYEE_ID) AS REPORTS_COUNT,
ROUND(AVG(M.AGE)) AS AVERAGE_AGE
FROM EMPLOYEES M JOIN EMPLOYEES E ON M.REPORTS_TO = E.EMPLOYEE_ID 
GROUP BY E.EMPLOYEE_ID