-- Write your PostgreSQL query statement below
WITH TOTAL_SALES AS (
    SELECT 
        USER_ID, 
        S.PRODUCT_ID, 
        P.PRICE, 
        S.QUANTITY
    FROM SALES S LEFT JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
)
SELECT
    USER_ID, COALESCE(SUM(QUANTITY*PRICE),0) AS SPENDING
FROM TOTAL_SALES 
GROUP BY USER_ID
ORDER BY SPENDING DESC, USER_ID