# Write your MySQL query statement below

WITH CTE AS (
SELECT 
T.PAID_BY AS USER_ID,  -AMOUNT AS MONEY
FROM TRANSACTIONS T INNER JOIN USERS U ON T.PAID_BY = U.USER_ID 
UNION ALL 
SELECT 
T.PAID_TO AS USER_ID,  AMOUNT AS MONEY
FROM TRANSACTIONS T INNER JOIN USERS U ON T.PAID_TO = U.USER_ID 
)
SELECT U2.USER_ID, U2.USER_NAME, IFNULL(U2.CREDIT + TT.MONEY,U2.CREDIT) AS CREDIT,
CASE WHEN IFNULL(U2.CREDIT + TT.MONEY,U2.CREDIT) < 0 THEN 'Yes' 
ELSE 'No' 
END AS CREDIT_LIMIT_BREACHED
FROM USERS U2 LEFT JOIN (
SELECT 
USER_ID, SUM(MONEY) AS MONEY
FROM CTE 
GROUP BY USER_ID 
) TT ON TT.USER_ID = U2.USER_ID 