# Write your MySQL query statement below
WITH ALL_FRIENDS AS (
SELECT 
    USER1_ID AS U1,
    USER2_ID AS U2
FROM FRIENDSHIP 
UNION ALL 
SELECT 
    USER2_ID AS U1,
    USER1_ID AS U2
FROM FRIENDSHIP 
),
COMMON_FRIENDS AS (
SELECT
F.USER1_ID, F.USER2_ID, A1.U2 AS USER1_FRIENDS, A2.U2 AS USER2_FRIENDS
FROM FRIENDSHIP F 
LEFT JOIN ALL_FRIENDS A1 ON F.USER1_ID = A1.U1
LEFT JOIN ALL_FRIENDS A2 ON F.USER2_ID = A2.U1
WHERE A1.U2 = A2.U2
)
SELECT 
USER1_ID, USER2_ID, COUNT(*) AS COMMON_FRIEND
FROM COMMON_FRIENDS 
GROUP BY USER1_ID, USER2_ID HAVING COUNT(*) > 2