-- Write your PostgreSQL query statement below
WITH FEB_MOVIES AS (
    SELECT 
    MR.*,M.TITLE
    FROM MOVIERATING MR JOIN MOVIES M ON MR.MOVIE_ID = M.MOVIE_ID
    WHERE TO_CHAR(CREATED_AT, 'YYYY-MM') = '2020-02'
),
FIRST_Q AS (
SELECT
U.NAME AS RESULTS
FROM MOVIERATING MR 
JOIN USERS U ON MR.USER_ID = U.USER_ID
GROUP BY MR.USER_ID, U.NAME ORDER BY COUNT(DISTINCT MR.MOVIE_ID) DESC, U.NAME ASC LIMIT 1
),
SECOND_Q AS (
SELECT
TITLE AS RESULTS
FROM FEB_MOVIES GROUP BY TITLE 
ORDER BY AVG(RATING) DESC, TITLE ASC LIMIT 1
)
SELECT * FROM FIRST_Q
UNION ALL 
SELECT * FROM SECOND_Q

