-- Write your PostgreSQL query statement below
WITH TT AS (
SELECT 
S.USER_ID,
S.PRODUCT_ID, 
SUM(S.QUANTITY * P.PRICE) AS TOTAL
FROM SALES S JOIN PRODUCT P ON S.PRODUCT_ID = P.PRODUCT_ID
GROUP BY S.USER_ID,S.PRODUCT_ID
)
SELECT USER_ID, PRODUCT_ID FROM(
SELECT *, RANK() OVER (PARTITION BY USER_ID ORDER BY TOTAL DESC) as rnk FROM TT
) where rnk = 1
