-- Write your PostgreSQL query statement below
WITH RANKED_EMPLOYEES AS (
SELECT
ID, NAME, SALARY, DEPARTMENTID, RANK() OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RNK
FROM EMPLOYEE
)
SELECT
D.NAME AS DEPARTMENT,
RE.NAME AS EMPLOYEE,
RE.SALARY 
FROM DEPARTMENT D LEFT JOIN RANKED_EMPLOYEES RE
ON D.ID = RE.DEPARTMENTID
 WHERE RNK = 1
 