# Write your MySQL query statement below

# WITH TT AS 
# (SELECT D.NAME AS 'DEPARTMENT', MAX(E.SALARY) AS MAX_SALARY
# FROM EMPLOYEE E INNER JOIN DEPARTMENT D ON E.DEPARTMENTID = D.ID
# GROUP BY E.DEPARTMENTID)



SELECT DNAME AS DEPARTMENT, ENAME AS EMPLOYEE, IFNULL(SALARY,0) AS SALARY FROM (
SELECT 
D.NAME AS DNAME, RANK() OVER(PARTITION BY D.NAME ORDER BY E.SALARY DESC) AS RNK, E.NAME AS ENAME, E.SALARY
FROM DEPARTMENT D INNER JOIN EMPLOYEE E ON D.ID = E.DEPARTMENTID
) TT WHERE TT.RNK = 1;












-- SELECT 
-- D2.NAME 'DEPARTMENT', E2.NAME 'EMPLOYEE', E2.SALARY AS 'SALARY' FROM EMPLOYEE E2 INNER JOIN DEPARTMENT D2 ON E2.DEPARTMENTID = D2.ID WHERE 
-- E2.SALARY = (SELECT MAX(E3.SALARY) FROM EMPLOYEE E3 WHERE E3.DEPARTMENTID = E2.DEPARTMENTID GROUP BY E3.DEPARTMENTID );

# (SELECT TT.MAX_SALARY)
# FROM EMPLOYEE E2 INNER JOIN DEPARTMENT D2 ON E2.DEPARTMENTID = D2.ID;