-- Write your PostgreSQL query statement below
WITH TT AS (SELECT
REQUESTER_ID AS A,
ACCEPTER_ID AS B
FROM REQUESTACCEPTED 
UNION
SELECT ACCEPTER_ID AS A,
REQUESTER_ID AS B
FROM  REQUESTACCEPTED
)
SELECT
A AS ID, COUNT(DISTINCT B) AS NUM 
FROM TT GROUP BY A
ORDER BY NUM DESC LIMIT 1