-- Write your PostgreSQL query statement below

WITH TT AS (
SELECT
O.CUSTOMER_ID, O.PRODUCT_ID,
COUNT(*) AS NUM_PRODUCTS
FROM ORDERS O 
JOIN PRODUCTS P ON O.PRODUCT_ID = P.PRODUCT_ID
GROUP BY O.CUSTOMER_ID, O.PRODUCT_ID
ORDER BY O.CUSTOMER_ID
), RANKED AS (
SELECT 
*, RANK() OVER(PARTITION BY CUSTOMER_ID ORDER BY NUM_PRODUCTS DESC) AS RNK
FROM TT
)
SELECT
C.CUSTOMER_ID, 
R.PRODUCT_ID, 
P.PRODUCT_NAME
FROM CUSTOMERS C LEFT JOIN (SELECT * FROM RANKED WHERE RNK = 1) R ON C.CUSTOMER_ID = R.CUSTOMER_ID
JOIN PRODUCTS P ON P.PRODUCT_ID = R.PRODUCT_ID
