-- Write your PostgreSQL query statement below
WITH TT AS (
SELECT 
PERSON_ID, PERSON_NAME,
WEIGHT, SUM(WEIGHT) OVER(ORDER BY TURN) AS CUMSUM
FROM QUEUE 
)
SELECT PERSON_NAME FROM TT WHERE CUMSUM <= 1000 ORDER BY CUMSUM DESC LIMIT 1