# Write your MySQL query statement below

WITH T1 AS (
SELECT 
FOLLOWEE AS FOLLOWER, COUNT(*) AS NUM FROM FOLLOW 
GROUP BY FOLLOWEE HAVING COUNT(*) > 0 
),
 T2 AS (
   SELECT  FOLLOWER AS FOLLOWER, COUNT(*) AS NUM FROM FOLLOW 
GROUP BY FOLLOWER
HAVING COUNT(*) > 0 
)
SELECT * FROM T1 WHERE T1.FOLLOWER  IN (SELECT FOLLOWER FROM T2)
ORDER BY T1.FOLLOWER
