-- Write your PostgreSQL query statement below
WITH WEATHER_TYPES AS (
SELECT
COUNTRY_ID,
CASE WHEN AVG(WEATHER_STATE) <= 15 THEN 'Cold'
WHEN AVG(WEATHER_STATE) >= 25 THEN 'Hot'
ELSE 'Warm' END AS WEATHER_TYPE
FROM WEATHER W
where TO_CHAR(W.DAY, 'YYYY-MM') = '2019-11'
GROUP BY COUNTRY_ID
)
SELECT
C.country_name, 
COALESCE(WT.WEATHER_TYPE, 'WARM') AS WEATHER_TYPE
FROM COUNTRIES C JOIN WEATHER_TYPES WT 
ON C.COUNTRY_ID = WT.COUNTRY_ID

